name: Update Recent Activity

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정(00:00 UTC) 자동 업데이트
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Update README with recent activity"
          MAX_LINES: 5
